# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Alamofire', '>= 1.2.2' # Swift pod
  pod 'SwiftyJSON'
  use_frameworks!

  # Pods for Test

end
